name: dopamine120_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

workspace:
  - apps/dopamine120
  - packages/core
  - packages/dopamine_ui
  - packages/dopamine_ui/example
  - packages/logger
  - packages/platform_bridge
  - packages/platform_bridge/example

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
